### ISSUE TITLE
Error training model when using GPU

### ISSUE THREAD

**Issue by Calebium** [camlab-bioml/astir#10]
Thank you for release this very useful tool. When I was trying to train the model for cell type following the tutorial, I got the following error:

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/8196285/140834866-0c60cad9-8e60-4d45-8f0d-da35cb582618.png">

Looks like some tensors were assigned to the GPU and some were not. In astir.py it seems the detected device type (CPU or GPU) was not passed on to the newly created CellTypeModel objects, so if I add 'self._device,' to line 157 of astir.py, then the error goes away.

I hope that makes sense! Thanks again!

Caleb

**Comment by kieranrcampbell** [comment]
Hi Caleb

Thanks so much for this! Would you like to submit a pull request for the fix to be listed as a contributor? If not I can add the code.

Thanks!

**Comment by Calebium** [comment]
Yes I can submit a pull request for this. Will do this today.

Caleb

**Comment by Calebium** [comment]
Pull request submitted. Thanks!

Caleb

**Comment by kieranrcampbell** [comment]
Fab thank you so much!
