### ISSUE TITLE
Astir give me error message when the single-cell data is zscore normalized.

### ISSUE THREAD

**Issue by huanlity** [camlab-bioml/astir#18]
I am having the error message as shown below when the single-cell data is zscore noralized. Do you have any idea how to fix it? Also, what is your recommended normalization methods for single-cell data derived from multiplexed imaging data (such as CODEX) before put it through Astir? Thank you!

zscore calculation;
1. `df_after = df_after.apply(stats.zscore)`

2.
```
for c in df_after.columns:
            df_after[c] = (df_after[c] - df_after[c].mean()) / df_after[c].std()
```

![Screen Shot 2022-03-03 at 12 58 11 PM](https://user-images.githubusercontent.com/26349803/156624280-06567a7b-bcbf-4cf5-9acb-86bb4fb91a88.png)

**Comment by kieranrcampbell** [comment]
Hi @huanlity 

Astir is designed to work on non-negative expression data, so negative input values aren't allowed. We should have a more informative error message than this though (raised also in #19).

Recommended normalization is `arcsinh(x/c)` where `x` is the raw expression data and `c` is a user set cofactor (5 is a good value to start with).

Let me know if any other questions.
