### ISSUE TITLE
Debug auto-assigned parameters "ValueError: The parameter loc has invalid values"

### ISSUE THREAD

**Issue by raymond301** [camlab-bioml/astir#19]
I'm trying to develop a model on a new dataset, and am getting a new error I have not encountered before...but it's not descriptive enough to understand the origin of the issue.

Where do I even begin to de-bug this?
`
ValueError: The parameter loc has invalid values
`

![Screen Shot 2022-03-03 at 3 45 06 PM](https://user-images.githubusercontent.com/392344/156657940-e4533d78-f56c-4e35-ad4d-5c2f4a07ef57.png)

**Comment by raymond301** [comment]
I'm unsure of the crux of the issue...but my original data frame was normalized with values of -2 to 2...when I add a "c+2" constant value transformation to everything...this error goes away.

Thus, I am prematurely concluding that this bug is from the data submitted containing negative values...as that is really the only thing I changed, to get this to work.

You may close this issue report, if you wish...but will you please add either documentation or a more comprehensive error warning in a future build.

**Comment by kieranrcampbell** [comment]
Hi @raymond301 

Yes astir operates only on non-negative expression values since "0" has a special meaning (ie not expressed). Adding 2 as a workaround probably a good enough fix. I'll leave this issue open to remind us to make a more informative error message (I thought there was one).

Thanks!

**Comment by huanlity** [comment]
@kieranrcampbell Thanks for the information, this is helpful!
