### ISSUE TITLE
Is it possible to use a pre-trained Astir model to infer cell types on new data?

### ISSUE THREAD

**Issue by Calebium** [camlab-bioml/astir#21]
Hi,

From the Astir API it appears that with each new batch of data, the Astir model needs to be trained for that batch in order to infer cell types. Is it possible, with the current API, to train a model to convergence with training data, and then use that model in the future for inference of yet-unseen data (provided that the intensity normalization strategies are the same)? This will be helpful for projects with datasets that are too large to fit into one training (so we can randomly select a subset for training, and infer the rest), and increase the usability of previously trained models.

Thanks!

Caleb

**Comment by kieranrcampbell** [comment]
Hi @Calebium 

I think the `ast.predict_celltypes(...)` function is what you're looking for, that takes a new dataset and predicts using the trained model, does that work?

**Comment by cdub3575** [comment]
Hello, 

I trained ASTIR on a subset of my dataset. Then I open my full dataset and try to run the trained ASTIR on it but I have the following error :

```
df_full = pd.read_csv(".../intensities_25_markers.csv", index_col=0)
ast.predict_celltypes(df_full)
```

AttributeError: 'DataFrame' object has no attribute 'get_classes'

Thank you !
