### ISSUE TITLE
Does Astir work linearly through the phenotype YAML file?

### ISSUE THREAD

**Issue by Calebium** [camlab-bioml/astir#34]
Does Astir work linearly through the phenotype YAML file (i.e. does it find the first phenotyped population on the list, and then for the remaining population, apply the second phenotype out of what is left, etc)? Or does it apply all the phenotypes from the YAML file to the entire cell population at once?

Thank you!

Caleb

**Comment by kieranrcampbell** [comment]
Hi Caleb

It simultaneously optimizes a joint objective (likelihood) reasoning over all states at once. If you wanted to do one at a time, you would have to specify multiple yaml files and chain together the logic, e.g. you would first discern epithelial vs immune, then subset to immune, then T vs B etc.

Hope that clarifies,

Kieran
