### ISSUE TITLE
What is alpha?

### ISSUE THREAD

**Issue by xuefei-wang** [camlab-bioml/astir#9]
https://github.com/camlab-bioml/astir/blob/2e1ad5bbe752feab68a67f460552c3e91c4143c4/astir/models/celltype.py#L202

Hi, I was trying to understand your elbo construction. But I don't quite understand what is `alpha`. A little explanation would be appreciated. Besides, can you write down the equation you are using for elbo?

Thanks!

**Comment by kieranrcampbell** [comment]
Hi @xuefei-wang 

`alpha` is the prior on cluster (here: cell type) membership, so `p(z_n=c) = \alpha_c`. Hope that's helpful

**Comment by xuefei-wang** [comment]
Thanks! That's helpful.

**Comment by xuefei-wang** [comment]
Hi, sorry to bother you again. I am looking at the `elbo` loss and do not quite understand why you formulate it this way.

https://github.com/camlab-bioml/astir/blob/2e1ad5bbe752feab68a67f460552c3e91c4143c4/astir/models/celltype.py#L206

My understanding would be：
`elbo = (gamma * (log_p_y_on_c + mix_prior - log_gamma)).sum()`

Am I missing anything here?
